# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twupdate}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Klaas Jan Wierenga"]
  s.date = %q{2010-09-03}
  s.description = %q{twupdate is a command line twitter update client that uses OAuth to connect to twitter. Example use is to send twitter update from within QuickSilver on Mac OSX.}
  s.email = %q{k.j.wierenga@gmail.com}
  s.executables = ["twupdate", "twupdate_oauth_setup"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "VERSION"
  ]
  s.homepage = %q{http://github.com/kjwierenga/twupdate}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{twupdate is a command line twitter update client}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/twupdate_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<twitter>, [">= 0.9.8"])
      s.add_runtime_dependency(%q<oauth>, [">= 0.4.3"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<twitter>, [">= 0.9.8"])
      s.add_dependency(%q<oauth>, [">= 0.4.3"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<twitter>, [">= 0.9.8"])
    s.add_dependency(%q<oauth>, [">= 0.4.3"])
  end
end

